spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/sys_base?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=UTF8
        username: root
        password: h626551861
rm:
    security:
        disauth: /swagger-ui/*
#        enable: false
    generator:
        basePackage: com.rm.manager
        jooqPackage: com.rm.manager.jooq
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        password: medishare2019
#        url: jdbc:mysql://106.12.3.68:3306/dongbang?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=UTF8
#        username: medi
springfox:
    documentation:
        enabled: true
