spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://106.12.3.68:3306/dongbang?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=UTF8
        username: medi
        password: medishare2019
code:
    generator:
        basePackage: com.rm.manager
        driver-class-name: com.mysql.cj.jdbc.Driver
        jooqPackage: com.rm.manager.jooq
        password: medishare2019
        url: jdbc:mysql://106.12.3.68:3306/dongbang?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=UTF8
        username: medi
