/*
 * This file is generated by jOOQ.
 */
package com.rm.manager.jooq;


import com.rm.manager.jooq.tables.SysConfig;
import com.rm.manager.jooq.tables.SysDictionaryItem;
import com.rm.manager.jooq.tables.SysDictionaryType;
import com.rm.manager.jooq.tables.SysLoginLog;
import com.rm.manager.jooq.tables.SysMenu;
import com.rm.manager.jooq.tables.SysOrganization;
import com.rm.manager.jooq.tables.SysRole;
import com.rm.manager.jooq.tables.SysRoleMenu;
import com.rm.manager.jooq.tables.SysUser;
import com.rm.manager.jooq.tables.SysUserRole;
import com.rm.manager.jooq.tables.records.SysConfigRecord;
import com.rm.manager.jooq.tables.records.SysDictionaryItemRecord;
import com.rm.manager.jooq.tables.records.SysDictionaryTypeRecord;
import com.rm.manager.jooq.tables.records.SysLoginLogRecord;
import com.rm.manager.jooq.tables.records.SysMenuRecord;
import com.rm.manager.jooq.tables.records.SysOrganizationRecord;
import com.rm.manager.jooq.tables.records.SysRoleMenuRecord;
import com.rm.manager.jooq.tables.records.SysRoleRecord;
import com.rm.manager.jooq.tables.records.SysUserRecord;
import com.rm.manager.jooq.tables.records.SysUserRoleRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>sys_base</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<SysConfigRecord> PK_SYS_CONFIG = UniqueKeys0.PK_SYS_CONFIG;
    public static final UniqueKey<SysConfigRecord> SYNTHETIC_PK_SYS_CONFIG = UniqueKeys0.SYNTHETIC_PK_SYS_CONFIG;
    public static final UniqueKey<SysDictionaryItemRecord> PK_SYS_DICTIONARY_ITEM = UniqueKeys0.PK_SYS_DICTIONARY_ITEM;
    public static final UniqueKey<SysDictionaryItemRecord> SYNTHETIC_PK_SYS_DICTIONARY_ITEM = UniqueKeys0.SYNTHETIC_PK_SYS_DICTIONARY_ITEM;
    public static final UniqueKey<SysDictionaryTypeRecord> PK_SYS_DICTIONARY_TYPE = UniqueKeys0.PK_SYS_DICTIONARY_TYPE;
    public static final UniqueKey<SysDictionaryTypeRecord> SYNTHETIC_PK_SYS_DICTIONARY_TYPE = UniqueKeys0.SYNTHETIC_PK_SYS_DICTIONARY_TYPE;
    public static final UniqueKey<SysLoginLogRecord> PK_SYS_LOGIN_LOG = UniqueKeys0.PK_SYS_LOGIN_LOG;
    public static final UniqueKey<SysLoginLogRecord> SYNTHETIC_PK_SYS_LOGIN_LOG = UniqueKeys0.SYNTHETIC_PK_SYS_LOGIN_LOG;
    public static final UniqueKey<SysMenuRecord> PK_SYS_MENU = UniqueKeys0.PK_SYS_MENU;
    public static final UniqueKey<SysMenuRecord> SYNTHETIC_PK_SYS_MENU = UniqueKeys0.SYNTHETIC_PK_SYS_MENU;
    public static final UniqueKey<SysOrganizationRecord> PK_SYS_ORGANIZATION = UniqueKeys0.PK_SYS_ORGANIZATION;
    public static final UniqueKey<SysOrganizationRecord> SYNTHETIC_PK_SYS_ORGANIZATION = UniqueKeys0.SYNTHETIC_PK_SYS_ORGANIZATION;
    public static final UniqueKey<SysRoleRecord> PK_SYS_ROLE = UniqueKeys0.PK_SYS_ROLE;
    public static final UniqueKey<SysRoleRecord> SYNTHETIC_PK_SYS_ROLE = UniqueKeys0.SYNTHETIC_PK_SYS_ROLE;
    public static final UniqueKey<SysRoleMenuRecord> PK_SYS_ROLE_MENU = UniqueKeys0.PK_SYS_ROLE_MENU;
    public static final UniqueKey<SysRoleMenuRecord> SYNTHETIC_PK_SYS_ROLE_MENU = UniqueKeys0.SYNTHETIC_PK_SYS_ROLE_MENU;
    public static final UniqueKey<SysUserRecord> PK_SYS_USER = UniqueKeys0.PK_SYS_USER;
    public static final UniqueKey<SysUserRecord> SYNTHETIC_PK_SYS_USER = UniqueKeys0.SYNTHETIC_PK_SYS_USER;
    public static final UniqueKey<SysUserRoleRecord> PK_SYS_USER_ROLE = UniqueKeys0.PK_SYS_USER_ROLE;
    public static final UniqueKey<SysUserRoleRecord> SYNTHETIC_PK_SYS_USER_ROLE = UniqueKeys0.SYNTHETIC_PK_SYS_USER_ROLE;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<SysConfigRecord> PK_SYS_CONFIG = Internal.createUniqueKey(SysConfig.SYS_CONFIG, "PK_sys_config", new TableField[] { SysConfig.SYS_CONFIG.ID }, true);
        public static final UniqueKey<SysConfigRecord> SYNTHETIC_PK_SYS_CONFIG = Internal.createUniqueKey(SysConfig.SYS_CONFIG, "SYNTHETIC_PK_sys_config", new TableField[] { SysConfig.SYS_CONFIG.ID }, true);
        public static final UniqueKey<SysDictionaryItemRecord> PK_SYS_DICTIONARY_ITEM = Internal.createUniqueKey(SysDictionaryItem.SYS_DICTIONARY_ITEM, "PK_sys_dictionary_item", new TableField[] { SysDictionaryItem.SYS_DICTIONARY_ITEM.ID }, true);
        public static final UniqueKey<SysDictionaryItemRecord> SYNTHETIC_PK_SYS_DICTIONARY_ITEM = Internal.createUniqueKey(SysDictionaryItem.SYS_DICTIONARY_ITEM, "SYNTHETIC_PK_sys_dictionary_item", new TableField[] { SysDictionaryItem.SYS_DICTIONARY_ITEM.ID }, true);
        public static final UniqueKey<SysDictionaryTypeRecord> PK_SYS_DICTIONARY_TYPE = Internal.createUniqueKey(SysDictionaryType.SYS_DICTIONARY_TYPE, "PK_sys_dictionary_type", new TableField[] { SysDictionaryType.SYS_DICTIONARY_TYPE.ID }, true);
        public static final UniqueKey<SysDictionaryTypeRecord> SYNTHETIC_PK_SYS_DICTIONARY_TYPE = Internal.createUniqueKey(SysDictionaryType.SYS_DICTIONARY_TYPE, "SYNTHETIC_PK_sys_dictionary_type", new TableField[] { SysDictionaryType.SYS_DICTIONARY_TYPE.ID }, true);
        public static final UniqueKey<SysLoginLogRecord> PK_SYS_LOGIN_LOG = Internal.createUniqueKey(SysLoginLog.SYS_LOGIN_LOG, "PK_sys_login_log", new TableField[] { SysLoginLog.SYS_LOGIN_LOG.ID }, true);
        public static final UniqueKey<SysLoginLogRecord> SYNTHETIC_PK_SYS_LOGIN_LOG = Internal.createUniqueKey(SysLoginLog.SYS_LOGIN_LOG, "SYNTHETIC_PK_sys_login_log", new TableField[] { SysLoginLog.SYS_LOGIN_LOG.ID }, true);
        public static final UniqueKey<SysMenuRecord> PK_SYS_MENU = Internal.createUniqueKey(SysMenu.SYS_MENU, "PK_sys_menu", new TableField[] { SysMenu.SYS_MENU.ID }, true);
        public static final UniqueKey<SysMenuRecord> SYNTHETIC_PK_SYS_MENU = Internal.createUniqueKey(SysMenu.SYS_MENU, "SYNTHETIC_PK_sys_menu", new TableField[] { SysMenu.SYS_MENU.ID }, true);
        public static final UniqueKey<SysOrganizationRecord> PK_SYS_ORGANIZATION = Internal.createUniqueKey(SysOrganization.SYS_ORGANIZATION, "PK_sys_organization", new TableField[] { SysOrganization.SYS_ORGANIZATION.ID }, true);
        public static final UniqueKey<SysOrganizationRecord> SYNTHETIC_PK_SYS_ORGANIZATION = Internal.createUniqueKey(SysOrganization.SYS_ORGANIZATION, "SYNTHETIC_PK_sys_organization", new TableField[] { SysOrganization.SYS_ORGANIZATION.ID }, true);
        public static final UniqueKey<SysRoleRecord> PK_SYS_ROLE = Internal.createUniqueKey(SysRole.SYS_ROLE, "PK_sys_role", new TableField[] { SysRole.SYS_ROLE.ID }, true);
        public static final UniqueKey<SysRoleRecord> SYNTHETIC_PK_SYS_ROLE = Internal.createUniqueKey(SysRole.SYS_ROLE, "SYNTHETIC_PK_sys_role", new TableField[] { SysRole.SYS_ROLE.ID }, true);
        public static final UniqueKey<SysRoleMenuRecord> PK_SYS_ROLE_MENU = Internal.createUniqueKey(SysRoleMenu.SYS_ROLE_MENU, "PK_sys_role_menu", new TableField[] { SysRoleMenu.SYS_ROLE_MENU.ID }, true);
        public static final UniqueKey<SysRoleMenuRecord> SYNTHETIC_PK_SYS_ROLE_MENU = Internal.createUniqueKey(SysRoleMenu.SYS_ROLE_MENU, "SYNTHETIC_PK_sys_role_menu", new TableField[] { SysRoleMenu.SYS_ROLE_MENU.ID }, true);
        public static final UniqueKey<SysUserRecord> PK_SYS_USER = Internal.createUniqueKey(SysUser.SYS_USER, "PK_sys_user", new TableField[] { SysUser.SYS_USER.ID }, true);
        public static final UniqueKey<SysUserRecord> SYNTHETIC_PK_SYS_USER = Internal.createUniqueKey(SysUser.SYS_USER, "SYNTHETIC_PK_sys_user", new TableField[] { SysUser.SYS_USER.ID }, true);
        public static final UniqueKey<SysUserRoleRecord> PK_SYS_USER_ROLE = Internal.createUniqueKey(SysUserRole.SYS_USER_ROLE, "PK_sys_user_role", new TableField[] { SysUserRole.SYS_USER_ROLE.ID }, true);
        public static final UniqueKey<SysUserRoleRecord> SYNTHETIC_PK_SYS_USER_ROLE = Internal.createUniqueKey(SysUserRole.SYS_USER_ROLE, "SYNTHETIC_PK_sys_user_role", new TableField[] { SysUserRole.SYS_USER_ROLE.ID }, true);
    }
}
