/*
 * This file is generated by jOOQ.
 */
package com.rm.manager.jooq;


import com.rm.manager.jooq.tables.SysConfig;
import com.rm.manager.jooq.tables.SysDictionaryItem;
import com.rm.manager.jooq.tables.SysDictionaryType;
import com.rm.manager.jooq.tables.SysLoginLog;
import com.rm.manager.jooq.tables.SysMenu;
import com.rm.manager.jooq.tables.SysOrganization;
import com.rm.manager.jooq.tables.SysRole;
import com.rm.manager.jooq.tables.SysRoleMenu;
import com.rm.manager.jooq.tables.SysUser;
import com.rm.manager.jooq.tables.SysUserRole;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysBase extends SchemaImpl {

    private static final long serialVersionUID = -1555550807;

    /**
     * The reference instance of <code>sys_base</code>
     */
    public static final SysBase SYS_BASE = new SysBase();

    /**
     * The table <code>sys_base.sys_config</code>.
     */
    public final SysConfig SYS_CONFIG = SysConfig.SYS_CONFIG;

    /**
     * The table <code>sys_base.sys_dictionary_item</code>.
     */
    public final SysDictionaryItem SYS_DICTIONARY_ITEM = SysDictionaryItem.SYS_DICTIONARY_ITEM;

    /**
     * The table <code>sys_base.sys_dictionary_type</code>.
     */
    public final SysDictionaryType SYS_DICTIONARY_TYPE = SysDictionaryType.SYS_DICTIONARY_TYPE;

    /**
     * The table <code>sys_base.sys_login_log</code>.
     */
    public final SysLoginLog SYS_LOGIN_LOG = SysLoginLog.SYS_LOGIN_LOG;

    /**
     * The table <code>sys_base.sys_menu</code>.
     */
    public final SysMenu SYS_MENU = SysMenu.SYS_MENU;

    /**
     * The table <code>sys_base.sys_organization</code>.
     */
    public final SysOrganization SYS_ORGANIZATION = SysOrganization.SYS_ORGANIZATION;

    /**
     * The table <code>sys_base.sys_role</code>.
     */
    public final SysRole SYS_ROLE = SysRole.SYS_ROLE;

    /**
     * The table <code>sys_base.sys_role_menu</code>.
     */
    public final SysRoleMenu SYS_ROLE_MENU = SysRoleMenu.SYS_ROLE_MENU;

    /**
     * The table <code>sys_base.sys_user</code>.
     */
    public final SysUser SYS_USER = SysUser.SYS_USER;

    /**
     * The table <code>sys_base.sys_user_role</code>.
     */
    public final SysUserRole SYS_USER_ROLE = SysUserRole.SYS_USER_ROLE;

    /**
     * No further instances allowed
     */
    private SysBase() {
        super("sys_base", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            SysConfig.SYS_CONFIG,
            SysDictionaryItem.SYS_DICTIONARY_ITEM,
            SysDictionaryType.SYS_DICTIONARY_TYPE,
            SysLoginLog.SYS_LOGIN_LOG,
            SysMenu.SYS_MENU,
            SysOrganization.SYS_ORGANIZATION,
            SysRole.SYS_ROLE,
            SysRoleMenu.SYS_ROLE_MENU,
            SysUser.SYS_USER,
            SysUserRole.SYS_USER_ROLE);
    }
}
