/*
 * This file is generated by jOOQ.
 */
package com.rm.manager.jooq;


import com.rm.manager.jooq.tables.SysConfig;
import com.rm.manager.jooq.tables.SysDictionaryItem;
import com.rm.manager.jooq.tables.SysDictionaryType;
import com.rm.manager.jooq.tables.SysLoginLog;
import com.rm.manager.jooq.tables.SysMenu;
import com.rm.manager.jooq.tables.SysOrganization;
import com.rm.manager.jooq.tables.SysRole;
import com.rm.manager.jooq.tables.SysRoleMenu;
import com.rm.manager.jooq.tables.SysUser;
import com.rm.manager.jooq.tables.SysUserRole;


/**
 * Convenience access to all tables in sys_base
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>sys_base.sys_config</code>.
     */
    public static final SysConfig SYS_CONFIG = SysConfig.SYS_CONFIG;

    /**
     * The table <code>sys_base.sys_dictionary_item</code>.
     */
    public static final SysDictionaryItem SYS_DICTIONARY_ITEM = SysDictionaryItem.SYS_DICTIONARY_ITEM;

    /**
     * The table <code>sys_base.sys_dictionary_type</code>.
     */
    public static final SysDictionaryType SYS_DICTIONARY_TYPE = SysDictionaryType.SYS_DICTIONARY_TYPE;

    /**
     * The table <code>sys_base.sys_login_log</code>.
     */
    public static final SysLoginLog SYS_LOGIN_LOG = SysLoginLog.SYS_LOGIN_LOG;

    /**
     * The table <code>sys_base.sys_menu</code>.
     */
    public static final SysMenu SYS_MENU = SysMenu.SYS_MENU;

    /**
     * The table <code>sys_base.sys_organization</code>.
     */
    public static final SysOrganization SYS_ORGANIZATION = SysOrganization.SYS_ORGANIZATION;

    /**
     * The table <code>sys_base.sys_role</code>.
     */
    public static final SysRole SYS_ROLE = SysRole.SYS_ROLE;

    /**
     * The table <code>sys_base.sys_role_menu</code>.
     */
    public static final SysRoleMenu SYS_ROLE_MENU = SysRoleMenu.SYS_ROLE_MENU;

    /**
     * The table <code>sys_base.sys_user</code>.
     */
    public static final SysUser SYS_USER = SysUser.SYS_USER;

    /**
     * The table <code>sys_base.sys_user_role</code>.
     */
    public static final SysUserRole SYS_USER_ROLE = SysUserRole.SYS_USER_ROLE;
}
