/*
 * This file is generated by jOOQ.
 */
package com.rm.manager.jooq.tables.records;


import com.rm.manager.jooq.tables.SysConfig;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysConfigRecord extends UpdatableRecordImpl<SysConfigRecord> implements Record6<String, LocalDateTime, LocalDateTime, String, String, String> {

    private static final long serialVersionUID = -716770974;

    /**
     * Setter for <code>sys_base.sys_config.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>sys_base.sys_config.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>sys_base.sys_config.create_date</code>.
     */
    public void setCreateDate(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>sys_base.sys_config.create_date</code>.
     */
    public LocalDateTime getCreateDate() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>sys_base.sys_config.update_date</code>.
     */
    public void setUpdateDate(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>sys_base.sys_config.update_date</code>.
     */
    public LocalDateTime getUpdateDate() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>sys_base.sys_config.key</code>.
     */
    public void setKey(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>sys_base.sys_config.key</code>.
     */
    public String getKey() {
        return (String) get(3);
    }

    /**
     * Setter for <code>sys_base.sys_config.value</code>.
     */
    public void setValue(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>sys_base.sys_config.value</code>.
     */
    public String getValue() {
        return (String) get(4);
    }

    /**
     * Setter for <code>sys_base.sys_config.remark</code>.
     */
    public void setRemark(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>sys_base.sys_config.remark</code>.
     */
    public String getRemark() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<String, LocalDateTime, LocalDateTime, String, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<String, LocalDateTime, LocalDateTime, String, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return SysConfig.SYS_CONFIG.ID;
    }

    @Override
    public Field<LocalDateTime> field2() {
        return SysConfig.SYS_CONFIG.CREATE_DATE;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return SysConfig.SYS_CONFIG.UPDATE_DATE;
    }

    @Override
    public Field<String> field4() {
        return SysConfig.SYS_CONFIG.KEY;
    }

    @Override
    public Field<String> field5() {
        return SysConfig.SYS_CONFIG.VALUE;
    }

    @Override
    public Field<String> field6() {
        return SysConfig.SYS_CONFIG.REMARK;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public LocalDateTime component2() {
        return getCreateDate();
    }

    @Override
    public LocalDateTime component3() {
        return getUpdateDate();
    }

    @Override
    public String component4() {
        return getKey();
    }

    @Override
    public String component5() {
        return getValue();
    }

    @Override
    public String component6() {
        return getRemark();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public LocalDateTime value2() {
        return getCreateDate();
    }

    @Override
    public LocalDateTime value3() {
        return getUpdateDate();
    }

    @Override
    public String value4() {
        return getKey();
    }

    @Override
    public String value5() {
        return getValue();
    }

    @Override
    public String value6() {
        return getRemark();
    }

    @Override
    public SysConfigRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public SysConfigRecord value2(LocalDateTime value) {
        setCreateDate(value);
        return this;
    }

    @Override
    public SysConfigRecord value3(LocalDateTime value) {
        setUpdateDate(value);
        return this;
    }

    @Override
    public SysConfigRecord value4(String value) {
        setKey(value);
        return this;
    }

    @Override
    public SysConfigRecord value5(String value) {
        setValue(value);
        return this;
    }

    @Override
    public SysConfigRecord value6(String value) {
        setRemark(value);
        return this;
    }

    @Override
    public SysConfigRecord values(String value1, LocalDateTime value2, LocalDateTime value3, String value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SysConfigRecord
     */
    public SysConfigRecord() {
        super(SysConfig.SYS_CONFIG);
    }

    /**
     * Create a detached, initialised SysConfigRecord
     */
    public SysConfigRecord(String id, LocalDateTime createDate, LocalDateTime updateDate, String key, String value, String remark) {
        super(SysConfig.SYS_CONFIG);

        set(0, id);
        set(1, createDate);
        set(2, updateDate);
        set(3, key);
        set(4, value);
        set(5, remark);
    }
}
