/*
 * This file is generated by jOOQ.
 */
package com.rm.manager.jooq.tables.records;


import com.rm.manager.jooq.tables.SysDictionaryType;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysDictionaryTypeRecord extends UpdatableRecordImpl<SysDictionaryTypeRecord> implements Record5<String, LocalDateTime, LocalDateTime, String, String> {

    private static final long serialVersionUID = -88841166;

    /**
     * Setter for <code>sys_base.sys_dictionary_type.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>sys_base.sys_dictionary_type.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>sys_base.sys_dictionary_type.create_date</code>.
     */
    public void setCreateDate(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>sys_base.sys_dictionary_type.create_date</code>.
     */
    public LocalDateTime getCreateDate() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>sys_base.sys_dictionary_type.update_date</code>.
     */
    public void setUpdateDate(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>sys_base.sys_dictionary_type.update_date</code>.
     */
    public LocalDateTime getUpdateDate() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>sys_base.sys_dictionary_type.remark</code>.
     */
    public void setRemark(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>sys_base.sys_dictionary_type.remark</code>.
     */
    public String getRemark() {
        return (String) get(3);
    }

    /**
     * Setter for <code>sys_base.sys_dictionary_type.type</code>.
     */
    public void setType(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>sys_base.sys_dictionary_type.type</code>.
     */
    public String getType() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<String, LocalDateTime, LocalDateTime, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<String, LocalDateTime, LocalDateTime, String, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return SysDictionaryType.SYS_DICTIONARY_TYPE.ID;
    }

    @Override
    public Field<LocalDateTime> field2() {
        return SysDictionaryType.SYS_DICTIONARY_TYPE.CREATE_DATE;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return SysDictionaryType.SYS_DICTIONARY_TYPE.UPDATE_DATE;
    }

    @Override
    public Field<String> field4() {
        return SysDictionaryType.SYS_DICTIONARY_TYPE.REMARK;
    }

    @Override
    public Field<String> field5() {
        return SysDictionaryType.SYS_DICTIONARY_TYPE.TYPE;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public LocalDateTime component2() {
        return getCreateDate();
    }

    @Override
    public LocalDateTime component3() {
        return getUpdateDate();
    }

    @Override
    public String component4() {
        return getRemark();
    }

    @Override
    public String component5() {
        return getType();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public LocalDateTime value2() {
        return getCreateDate();
    }

    @Override
    public LocalDateTime value3() {
        return getUpdateDate();
    }

    @Override
    public String value4() {
        return getRemark();
    }

    @Override
    public String value5() {
        return getType();
    }

    @Override
    public SysDictionaryTypeRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public SysDictionaryTypeRecord value2(LocalDateTime value) {
        setCreateDate(value);
        return this;
    }

    @Override
    public SysDictionaryTypeRecord value3(LocalDateTime value) {
        setUpdateDate(value);
        return this;
    }

    @Override
    public SysDictionaryTypeRecord value4(String value) {
        setRemark(value);
        return this;
    }

    @Override
    public SysDictionaryTypeRecord value5(String value) {
        setType(value);
        return this;
    }

    @Override
    public SysDictionaryTypeRecord values(String value1, LocalDateTime value2, LocalDateTime value3, String value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SysDictionaryTypeRecord
     */
    public SysDictionaryTypeRecord() {
        super(SysDictionaryType.SYS_DICTIONARY_TYPE);
    }

    /**
     * Create a detached, initialised SysDictionaryTypeRecord
     */
    public SysDictionaryTypeRecord(String id, LocalDateTime createDate, LocalDateTime updateDate, String remark, String type) {
        super(SysDictionaryType.SYS_DICTIONARY_TYPE);

        set(0, id);
        set(1, createDate);
        set(2, updateDate);
        set(3, remark);
        set(4, type);
    }
}
