/*
 * This file is generated by jOOQ.
 */
package com.rm.manager.jooq.tables.records;


import com.rm.manager.jooq.tables.SysDictionaryItem;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysDictionaryItemRecord extends UpdatableRecordImpl<SysDictionaryItemRecord> implements Record7<String, LocalDateTime, LocalDateTime, String, String, String, String> {

    private static final long serialVersionUID = -479780152;

    /**
     * Setter for <code>sys_base.sys_dictionary_item.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>sys_base.sys_dictionary_item.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>sys_base.sys_dictionary_item.create_date</code>.
     */
    public void setCreateDate(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>sys_base.sys_dictionary_item.create_date</code>.
     */
    public LocalDateTime getCreateDate() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>sys_base.sys_dictionary_item.update_date</code>.
     */
    public void setUpdateDate(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>sys_base.sys_dictionary_item.update_date</code>.
     */
    public LocalDateTime getUpdateDate() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>sys_base.sys_dictionary_item.type_id</code>.
     */
    public void setTypeId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>sys_base.sys_dictionary_item.type_id</code>.
     */
    public String getTypeId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>sys_base.sys_dictionary_item.key</code>.
     */
    public void setKey(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>sys_base.sys_dictionary_item.key</code>.
     */
    public String getKey() {
        return (String) get(4);
    }

    /**
     * Setter for <code>sys_base.sys_dictionary_item.value</code>.
     */
    public void setValue(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>sys_base.sys_dictionary_item.value</code>.
     */
    public String getValue() {
        return (String) get(5);
    }

    /**
     * Setter for <code>sys_base.sys_dictionary_item.remark</code>.
     */
    public void setRemark(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>sys_base.sys_dictionary_item.remark</code>.
     */
    public String getRemark() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<String, LocalDateTime, LocalDateTime, String, String, String, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<String, LocalDateTime, LocalDateTime, String, String, String, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return SysDictionaryItem.SYS_DICTIONARY_ITEM.ID;
    }

    @Override
    public Field<LocalDateTime> field2() {
        return SysDictionaryItem.SYS_DICTIONARY_ITEM.CREATE_DATE;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return SysDictionaryItem.SYS_DICTIONARY_ITEM.UPDATE_DATE;
    }

    @Override
    public Field<String> field4() {
        return SysDictionaryItem.SYS_DICTIONARY_ITEM.TYPE_ID;
    }

    @Override
    public Field<String> field5() {
        return SysDictionaryItem.SYS_DICTIONARY_ITEM.KEY;
    }

    @Override
    public Field<String> field6() {
        return SysDictionaryItem.SYS_DICTIONARY_ITEM.VALUE;
    }

    @Override
    public Field<String> field7() {
        return SysDictionaryItem.SYS_DICTIONARY_ITEM.REMARK;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public LocalDateTime component2() {
        return getCreateDate();
    }

    @Override
    public LocalDateTime component3() {
        return getUpdateDate();
    }

    @Override
    public String component4() {
        return getTypeId();
    }

    @Override
    public String component5() {
        return getKey();
    }

    @Override
    public String component6() {
        return getValue();
    }

    @Override
    public String component7() {
        return getRemark();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public LocalDateTime value2() {
        return getCreateDate();
    }

    @Override
    public LocalDateTime value3() {
        return getUpdateDate();
    }

    @Override
    public String value4() {
        return getTypeId();
    }

    @Override
    public String value5() {
        return getKey();
    }

    @Override
    public String value6() {
        return getValue();
    }

    @Override
    public String value7() {
        return getRemark();
    }

    @Override
    public SysDictionaryItemRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public SysDictionaryItemRecord value2(LocalDateTime value) {
        setCreateDate(value);
        return this;
    }

    @Override
    public SysDictionaryItemRecord value3(LocalDateTime value) {
        setUpdateDate(value);
        return this;
    }

    @Override
    public SysDictionaryItemRecord value4(String value) {
        setTypeId(value);
        return this;
    }

    @Override
    public SysDictionaryItemRecord value5(String value) {
        setKey(value);
        return this;
    }

    @Override
    public SysDictionaryItemRecord value6(String value) {
        setValue(value);
        return this;
    }

    @Override
    public SysDictionaryItemRecord value7(String value) {
        setRemark(value);
        return this;
    }

    @Override
    public SysDictionaryItemRecord values(String value1, LocalDateTime value2, LocalDateTime value3, String value4, String value5, String value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SysDictionaryItemRecord
     */
    public SysDictionaryItemRecord() {
        super(SysDictionaryItem.SYS_DICTIONARY_ITEM);
    }

    /**
     * Create a detached, initialised SysDictionaryItemRecord
     */
    public SysDictionaryItemRecord(String id, LocalDateTime createDate, LocalDateTime updateDate, String typeId, String key, String value, String remark) {
        super(SysDictionaryItem.SYS_DICTIONARY_ITEM);

        set(0, id);
        set(1, createDate);
        set(2, updateDate);
        set(3, typeId);
        set(4, key);
        set(5, value);
        set(6, remark);
    }
}
