/*
 * This file is generated by jOOQ.
 */
package com.rm.manager.jooq.tables.records;


import com.rm.manager.jooq.tables.SysLoginLog;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysLoginLogRecord extends UpdatableRecordImpl<SysLoginLogRecord> implements Record7<String, LocalDateTime, LocalDateTime, String, String, String, String> {

    private static final long serialVersionUID = 128857742;

    /**
     * Setter for <code>sys_base.sys_login_log.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>sys_base.sys_login_log.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>sys_base.sys_login_log.create_date</code>.
     */
    public void setCreateDate(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>sys_base.sys_login_log.create_date</code>.
     */
    public LocalDateTime getCreateDate() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>sys_base.sys_login_log.update_date</code>.
     */
    public void setUpdateDate(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>sys_base.sys_login_log.update_date</code>.
     */
    public LocalDateTime getUpdateDate() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>sys_base.sys_login_log.user_id</code>.
     */
    public void setUserId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>sys_base.sys_login_log.user_id</code>.
     */
    public String getUserId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>sys_base.sys_login_log.phone</code>.
     */
    public void setPhone(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>sys_base.sys_login_log.phone</code>.
     */
    public String getPhone() {
        return (String) get(4);
    }

    /**
     * Setter for <code>sys_base.sys_login_log.sys_info</code>.
     */
    public void setSysInfo(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>sys_base.sys_login_log.sys_info</code>.
     */
    public String getSysInfo() {
        return (String) get(5);
    }

    /**
     * Setter for <code>sys_base.sys_login_log.device_info</code>.
     */
    public void setDeviceInfo(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>sys_base.sys_login_log.device_info</code>.
     */
    public String getDeviceInfo() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<String, LocalDateTime, LocalDateTime, String, String, String, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<String, LocalDateTime, LocalDateTime, String, String, String, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return SysLoginLog.SYS_LOGIN_LOG.ID;
    }

    @Override
    public Field<LocalDateTime> field2() {
        return SysLoginLog.SYS_LOGIN_LOG.CREATE_DATE;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return SysLoginLog.SYS_LOGIN_LOG.UPDATE_DATE;
    }

    @Override
    public Field<String> field4() {
        return SysLoginLog.SYS_LOGIN_LOG.USER_ID;
    }

    @Override
    public Field<String> field5() {
        return SysLoginLog.SYS_LOGIN_LOG.PHONE;
    }

    @Override
    public Field<String> field6() {
        return SysLoginLog.SYS_LOGIN_LOG.SYS_INFO;
    }

    @Override
    public Field<String> field7() {
        return SysLoginLog.SYS_LOGIN_LOG.DEVICE_INFO;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public LocalDateTime component2() {
        return getCreateDate();
    }

    @Override
    public LocalDateTime component3() {
        return getUpdateDate();
    }

    @Override
    public String component4() {
        return getUserId();
    }

    @Override
    public String component5() {
        return getPhone();
    }

    @Override
    public String component6() {
        return getSysInfo();
    }

    @Override
    public String component7() {
        return getDeviceInfo();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public LocalDateTime value2() {
        return getCreateDate();
    }

    @Override
    public LocalDateTime value3() {
        return getUpdateDate();
    }

    @Override
    public String value4() {
        return getUserId();
    }

    @Override
    public String value5() {
        return getPhone();
    }

    @Override
    public String value6() {
        return getSysInfo();
    }

    @Override
    public String value7() {
        return getDeviceInfo();
    }

    @Override
    public SysLoginLogRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public SysLoginLogRecord value2(LocalDateTime value) {
        setCreateDate(value);
        return this;
    }

    @Override
    public SysLoginLogRecord value3(LocalDateTime value) {
        setUpdateDate(value);
        return this;
    }

    @Override
    public SysLoginLogRecord value4(String value) {
        setUserId(value);
        return this;
    }

    @Override
    public SysLoginLogRecord value5(String value) {
        setPhone(value);
        return this;
    }

    @Override
    public SysLoginLogRecord value6(String value) {
        setSysInfo(value);
        return this;
    }

    @Override
    public SysLoginLogRecord value7(String value) {
        setDeviceInfo(value);
        return this;
    }

    @Override
    public SysLoginLogRecord values(String value1, LocalDateTime value2, LocalDateTime value3, String value4, String value5, String value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SysLoginLogRecord
     */
    public SysLoginLogRecord() {
        super(SysLoginLog.SYS_LOGIN_LOG);
    }

    /**
     * Create a detached, initialised SysLoginLogRecord
     */
    public SysLoginLogRecord(String id, LocalDateTime createDate, LocalDateTime updateDate, String userId, String phone, String sysInfo, String deviceInfo) {
        super(SysLoginLog.SYS_LOGIN_LOG);

        set(0, id);
        set(1, createDate);
        set(2, updateDate);
        set(3, userId);
        set(4, phone);
        set(5, sysInfo);
        set(6, deviceInfo);
    }
}
