/*
 * This file is generated by jOOQ.
 */
package com.rm.manager.jooq.tables.records;


import com.rm.manager.jooq.tables.SysMenu;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysMenuRecord extends UpdatableRecordImpl<SysMenuRecord> implements Record8<String, LocalDateTime, LocalDateTime, String, String, String, String, String> {

    private static final long serialVersionUID = 1029390150;

    /**
     * Setter for <code>sys_base.sys_menu.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>sys_base.sys_menu.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>sys_base.sys_menu.create_date</code>.
     */
    public void setCreateDate(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>sys_base.sys_menu.create_date</code>.
     */
    public LocalDateTime getCreateDate() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>sys_base.sys_menu.update_date</code>.
     */
    public void setUpdateDate(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>sys_base.sys_menu.update_date</code>.
     */
    public LocalDateTime getUpdateDate() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>sys_base.sys_menu.name</code>.
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>sys_base.sys_menu.name</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>sys_base.sys_menu.path</code>.
     */
    public void setPath(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>sys_base.sys_menu.path</code>.
     */
    public String getPath() {
        return (String) get(4);
    }

    /**
     * Setter for <code>sys_base.sys_menu.pid</code>.
     */
    public void setPid(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>sys_base.sys_menu.pid</code>.
     */
    public String getPid() {
        return (String) get(5);
    }

    /**
     * Setter for <code>sys_base.sys_menu.type</code>.
     */
    public void setType(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>sys_base.sys_menu.type</code>.
     */
    public String getType() {
        return (String) get(6);
    }

    /**
     * Setter for <code>sys_base.sys_menu.code</code>.
     */
    public void setCode(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>sys_base.sys_menu.code</code>.
     */
    public String getCode() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<String, LocalDateTime, LocalDateTime, String, String, String, String, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<String, LocalDateTime, LocalDateTime, String, String, String, String, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return SysMenu.SYS_MENU.ID;
    }

    @Override
    public Field<LocalDateTime> field2() {
        return SysMenu.SYS_MENU.CREATE_DATE;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return SysMenu.SYS_MENU.UPDATE_DATE;
    }

    @Override
    public Field<String> field4() {
        return SysMenu.SYS_MENU.NAME;
    }

    @Override
    public Field<String> field5() {
        return SysMenu.SYS_MENU.PATH;
    }

    @Override
    public Field<String> field6() {
        return SysMenu.SYS_MENU.PID;
    }

    @Override
    public Field<String> field7() {
        return SysMenu.SYS_MENU.TYPE;
    }

    @Override
    public Field<String> field8() {
        return SysMenu.SYS_MENU.CODE;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public LocalDateTime component2() {
        return getCreateDate();
    }

    @Override
    public LocalDateTime component3() {
        return getUpdateDate();
    }

    @Override
    public String component4() {
        return getName();
    }

    @Override
    public String component5() {
        return getPath();
    }

    @Override
    public String component6() {
        return getPid();
    }

    @Override
    public String component7() {
        return getType();
    }

    @Override
    public String component8() {
        return getCode();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public LocalDateTime value2() {
        return getCreateDate();
    }

    @Override
    public LocalDateTime value3() {
        return getUpdateDate();
    }

    @Override
    public String value4() {
        return getName();
    }

    @Override
    public String value5() {
        return getPath();
    }

    @Override
    public String value6() {
        return getPid();
    }

    @Override
    public String value7() {
        return getType();
    }

    @Override
    public String value8() {
        return getCode();
    }

    @Override
    public SysMenuRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public SysMenuRecord value2(LocalDateTime value) {
        setCreateDate(value);
        return this;
    }

    @Override
    public SysMenuRecord value3(LocalDateTime value) {
        setUpdateDate(value);
        return this;
    }

    @Override
    public SysMenuRecord value4(String value) {
        setName(value);
        return this;
    }

    @Override
    public SysMenuRecord value5(String value) {
        setPath(value);
        return this;
    }

    @Override
    public SysMenuRecord value6(String value) {
        setPid(value);
        return this;
    }

    @Override
    public SysMenuRecord value7(String value) {
        setType(value);
        return this;
    }

    @Override
    public SysMenuRecord value8(String value) {
        setCode(value);
        return this;
    }

    @Override
    public SysMenuRecord values(String value1, LocalDateTime value2, LocalDateTime value3, String value4, String value5, String value6, String value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SysMenuRecord
     */
    public SysMenuRecord() {
        super(SysMenu.SYS_MENU);
    }

    /**
     * Create a detached, initialised SysMenuRecord
     */
    public SysMenuRecord(String id, LocalDateTime createDate, LocalDateTime updateDate, String name, String path, String pid, String type, String code) {
        super(SysMenu.SYS_MENU);

        set(0, id);
        set(1, createDate);
        set(2, updateDate);
        set(3, name);
        set(4, path);
        set(5, pid);
        set(6, type);
        set(7, code);
    }
}
