/*
 * This file is generated by jOOQ.
 */
package com.rm.manager.jooq.tables.records;


import com.rm.manager.jooq.tables.SysOrganization;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysOrganizationRecord extends UpdatableRecordImpl<SysOrganizationRecord> implements Record8<String, LocalDateTime, LocalDateTime, String, String, Integer, String, String> {

    private static final long serialVersionUID = 626725585;

    /**
     * Setter for <code>sys_base.sys_organization.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>sys_base.sys_organization.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>sys_base.sys_organization.create_date</code>.
     */
    public void setCreateDate(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>sys_base.sys_organization.create_date</code>.
     */
    public LocalDateTime getCreateDate() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>sys_base.sys_organization.update_date</code>.
     */
    public void setUpdateDate(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>sys_base.sys_organization.update_date</code>.
     */
    public LocalDateTime getUpdateDate() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>sys_base.sys_organization.name</code>.
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>sys_base.sys_organization.name</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>sys_base.sys_organization.pid</code>.
     */
    public void setPid(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>sys_base.sys_organization.pid</code>.
     */
    public String getPid() {
        return (String) get(4);
    }

    /**
     * Setter for <code>sys_base.sys_organization.full_id</code>.
     */
    public void setFullId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>sys_base.sys_organization.full_id</code>.
     */
    public Integer getFullId() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>sys_base.sys_organization.remark</code>.
     */
    public void setRemark(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>sys_base.sys_organization.remark</code>.
     */
    public String getRemark() {
        return (String) get(6);
    }

    /**
     * Setter for <code>sys_base.sys_organization.location</code>.
     */
    public void setLocation(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>sys_base.sys_organization.location</code>.
     */
    public String getLocation() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<String, LocalDateTime, LocalDateTime, String, String, Integer, String, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<String, LocalDateTime, LocalDateTime, String, String, Integer, String, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return SysOrganization.SYS_ORGANIZATION.ID;
    }

    @Override
    public Field<LocalDateTime> field2() {
        return SysOrganization.SYS_ORGANIZATION.CREATE_DATE;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return SysOrganization.SYS_ORGANIZATION.UPDATE_DATE;
    }

    @Override
    public Field<String> field4() {
        return SysOrganization.SYS_ORGANIZATION.NAME;
    }

    @Override
    public Field<String> field5() {
        return SysOrganization.SYS_ORGANIZATION.PID;
    }

    @Override
    public Field<Integer> field6() {
        return SysOrganization.SYS_ORGANIZATION.FULL_ID;
    }

    @Override
    public Field<String> field7() {
        return SysOrganization.SYS_ORGANIZATION.REMARK;
    }

    @Override
    public Field<String> field8() {
        return SysOrganization.SYS_ORGANIZATION.LOCATION;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public LocalDateTime component2() {
        return getCreateDate();
    }

    @Override
    public LocalDateTime component3() {
        return getUpdateDate();
    }

    @Override
    public String component4() {
        return getName();
    }

    @Override
    public String component5() {
        return getPid();
    }

    @Override
    public Integer component6() {
        return getFullId();
    }

    @Override
    public String component7() {
        return getRemark();
    }

    @Override
    public String component8() {
        return getLocation();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public LocalDateTime value2() {
        return getCreateDate();
    }

    @Override
    public LocalDateTime value3() {
        return getUpdateDate();
    }

    @Override
    public String value4() {
        return getName();
    }

    @Override
    public String value5() {
        return getPid();
    }

    @Override
    public Integer value6() {
        return getFullId();
    }

    @Override
    public String value7() {
        return getRemark();
    }

    @Override
    public String value8() {
        return getLocation();
    }

    @Override
    public SysOrganizationRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public SysOrganizationRecord value2(LocalDateTime value) {
        setCreateDate(value);
        return this;
    }

    @Override
    public SysOrganizationRecord value3(LocalDateTime value) {
        setUpdateDate(value);
        return this;
    }

    @Override
    public SysOrganizationRecord value4(String value) {
        setName(value);
        return this;
    }

    @Override
    public SysOrganizationRecord value5(String value) {
        setPid(value);
        return this;
    }

    @Override
    public SysOrganizationRecord value6(Integer value) {
        setFullId(value);
        return this;
    }

    @Override
    public SysOrganizationRecord value7(String value) {
        setRemark(value);
        return this;
    }

    @Override
    public SysOrganizationRecord value8(String value) {
        setLocation(value);
        return this;
    }

    @Override
    public SysOrganizationRecord values(String value1, LocalDateTime value2, LocalDateTime value3, String value4, String value5, Integer value6, String value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SysOrganizationRecord
     */
    public SysOrganizationRecord() {
        super(SysOrganization.SYS_ORGANIZATION);
    }

    /**
     * Create a detached, initialised SysOrganizationRecord
     */
    public SysOrganizationRecord(String id, LocalDateTime createDate, LocalDateTime updateDate, String name, String pid, Integer fullId, String remark, String location) {
        super(SysOrganization.SYS_ORGANIZATION);

        set(0, id);
        set(1, createDate);
        set(2, updateDate);
        set(3, name);
        set(4, pid);
        set(5, fullId);
        set(6, remark);
        set(7, location);
    }
}
