/*
 * This file is generated by jOOQ.
 */
package com.rm.manager.jooq.tables.records;


import com.rm.manager.jooq.tables.SysRole;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysRoleRecord extends UpdatableRecordImpl<SysRoleRecord> implements Record5<String, LocalDateTime, LocalDateTime, String, String> {

    private static final long serialVersionUID = -1410798076;

    /**
     * Setter for <code>sys_base.sys_role.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>sys_base.sys_role.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>sys_base.sys_role.create_date</code>.
     */
    public void setCreateDate(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>sys_base.sys_role.create_date</code>.
     */
    public LocalDateTime getCreateDate() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>sys_base.sys_role.update_date</code>.
     */
    public void setUpdateDate(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>sys_base.sys_role.update_date</code>.
     */
    public LocalDateTime getUpdateDate() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>sys_base.sys_role.role_name</code>.
     */
    public void setRoleName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>sys_base.sys_role.role_name</code>.
     */
    public String getRoleName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>sys_base.sys_role.remark</code>.
     */
    public void setRemark(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>sys_base.sys_role.remark</code>.
     */
    public String getRemark() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<String, LocalDateTime, LocalDateTime, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<String, LocalDateTime, LocalDateTime, String, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return SysRole.SYS_ROLE.ID;
    }

    @Override
    public Field<LocalDateTime> field2() {
        return SysRole.SYS_ROLE.CREATE_DATE;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return SysRole.SYS_ROLE.UPDATE_DATE;
    }

    @Override
    public Field<String> field4() {
        return SysRole.SYS_ROLE.ROLE_NAME;
    }

    @Override
    public Field<String> field5() {
        return SysRole.SYS_ROLE.REMARK;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public LocalDateTime component2() {
        return getCreateDate();
    }

    @Override
    public LocalDateTime component3() {
        return getUpdateDate();
    }

    @Override
    public String component4() {
        return getRoleName();
    }

    @Override
    public String component5() {
        return getRemark();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public LocalDateTime value2() {
        return getCreateDate();
    }

    @Override
    public LocalDateTime value3() {
        return getUpdateDate();
    }

    @Override
    public String value4() {
        return getRoleName();
    }

    @Override
    public String value5() {
        return getRemark();
    }

    @Override
    public SysRoleRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public SysRoleRecord value2(LocalDateTime value) {
        setCreateDate(value);
        return this;
    }

    @Override
    public SysRoleRecord value3(LocalDateTime value) {
        setUpdateDate(value);
        return this;
    }

    @Override
    public SysRoleRecord value4(String value) {
        setRoleName(value);
        return this;
    }

    @Override
    public SysRoleRecord value5(String value) {
        setRemark(value);
        return this;
    }

    @Override
    public SysRoleRecord values(String value1, LocalDateTime value2, LocalDateTime value3, String value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SysRoleRecord
     */
    public SysRoleRecord() {
        super(SysRole.SYS_ROLE);
    }

    /**
     * Create a detached, initialised SysRoleRecord
     */
    public SysRoleRecord(String id, LocalDateTime createDate, LocalDateTime updateDate, String roleName, String remark) {
        super(SysRole.SYS_ROLE);

        set(0, id);
        set(1, createDate);
        set(2, updateDate);
        set(3, roleName);
        set(4, remark);
    }
}
