/*
 * This file is generated by jOOQ.
 */
package com.rm.manager.jooq.tables.records;


import com.rm.manager.jooq.tables.SysRoleMenu;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysRoleMenuRecord extends UpdatableRecordImpl<SysRoleMenuRecord> implements Record5<String, LocalDateTime, LocalDateTime, String, String> {

    private static final long serialVersionUID = 400155453;

    /**
     * Setter for <code>sys_base.sys_role_menu.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>sys_base.sys_role_menu.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>sys_base.sys_role_menu.create_date</code>.
     */
    public void setCreateDate(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>sys_base.sys_role_menu.create_date</code>.
     */
    public LocalDateTime getCreateDate() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>sys_base.sys_role_menu.update_date</code>.
     */
    public void setUpdateDate(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>sys_base.sys_role_menu.update_date</code>.
     */
    public LocalDateTime getUpdateDate() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>sys_base.sys_role_menu.role_id</code>.
     */
    public void setRoleId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>sys_base.sys_role_menu.role_id</code>.
     */
    public String getRoleId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>sys_base.sys_role_menu.menu_id</code>.
     */
    public void setMenuId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>sys_base.sys_role_menu.menu_id</code>.
     */
    public String getMenuId() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<String, LocalDateTime, LocalDateTime, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<String, LocalDateTime, LocalDateTime, String, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return SysRoleMenu.SYS_ROLE_MENU.ID;
    }

    @Override
    public Field<LocalDateTime> field2() {
        return SysRoleMenu.SYS_ROLE_MENU.CREATE_DATE;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return SysRoleMenu.SYS_ROLE_MENU.UPDATE_DATE;
    }

    @Override
    public Field<String> field4() {
        return SysRoleMenu.SYS_ROLE_MENU.ROLE_ID;
    }

    @Override
    public Field<String> field5() {
        return SysRoleMenu.SYS_ROLE_MENU.MENU_ID;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public LocalDateTime component2() {
        return getCreateDate();
    }

    @Override
    public LocalDateTime component3() {
        return getUpdateDate();
    }

    @Override
    public String component4() {
        return getRoleId();
    }

    @Override
    public String component5() {
        return getMenuId();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public LocalDateTime value2() {
        return getCreateDate();
    }

    @Override
    public LocalDateTime value3() {
        return getUpdateDate();
    }

    @Override
    public String value4() {
        return getRoleId();
    }

    @Override
    public String value5() {
        return getMenuId();
    }

    @Override
    public SysRoleMenuRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public SysRoleMenuRecord value2(LocalDateTime value) {
        setCreateDate(value);
        return this;
    }

    @Override
    public SysRoleMenuRecord value3(LocalDateTime value) {
        setUpdateDate(value);
        return this;
    }

    @Override
    public SysRoleMenuRecord value4(String value) {
        setRoleId(value);
        return this;
    }

    @Override
    public SysRoleMenuRecord value5(String value) {
        setMenuId(value);
        return this;
    }

    @Override
    public SysRoleMenuRecord values(String value1, LocalDateTime value2, LocalDateTime value3, String value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SysRoleMenuRecord
     */
    public SysRoleMenuRecord() {
        super(SysRoleMenu.SYS_ROLE_MENU);
    }

    /**
     * Create a detached, initialised SysRoleMenuRecord
     */
    public SysRoleMenuRecord(String id, LocalDateTime createDate, LocalDateTime updateDate, String roleId, String menuId) {
        super(SysRoleMenu.SYS_ROLE_MENU);

        set(0, id);
        set(1, createDate);
        set(2, updateDate);
        set(3, roleId);
        set(4, menuId);
    }
}
