/*
 * This file is generated by jOOQ.
 */
package com.rm.manager.jooq.tables.records;


import com.rm.manager.jooq.tables.SysUser;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysUserRecord extends UpdatableRecordImpl<SysUserRecord> implements Record12<String, LocalDateTime, LocalDateTime, String, String, String, String, String, String, String, String, String> {

    private static final long serialVersionUID = -2004983309;

    /**
     * Setter for <code>sys_base.sys_user.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>sys_base.sys_user.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>sys_base.sys_user.create_date</code>.
     */
    public void setCreateDate(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>sys_base.sys_user.create_date</code>.
     */
    public LocalDateTime getCreateDate() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>sys_base.sys_user.update_date</code>.
     */
    public void setUpdateDate(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>sys_base.sys_user.update_date</code>.
     */
    public LocalDateTime getUpdateDate() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>sys_base.sys_user.org_id</code>.
     */
    public void setOrgId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>sys_base.sys_user.org_id</code>.
     */
    public String getOrgId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>sys_base.sys_user.data_level</code>.
     */
    public void setDataLevel(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>sys_base.sys_user.data_level</code>.
     */
    public String getDataLevel() {
        return (String) get(4);
    }

    /**
     * Setter for <code>sys_base.sys_user.name</code>.
     */
    public void setName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>sys_base.sys_user.name</code>.
     */
    public String getName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>sys_base.sys_user.avatar</code>.
     */
    public void setAvatar(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>sys_base.sys_user.avatar</code>.
     */
    public String getAvatar() {
        return (String) get(6);
    }

    /**
     * Setter for <code>sys_base.sys_user.idcard</code>.
     */
    public void setIdcard(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>sys_base.sys_user.idcard</code>.
     */
    public String getIdcard() {
        return (String) get(7);
    }

    /**
     * Setter for <code>sys_base.sys_user.sex</code>.
     */
    public void setSex(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>sys_base.sys_user.sex</code>.
     */
    public String getSex() {
        return (String) get(8);
    }

    /**
     * Setter for <code>sys_base.sys_user.phone</code>.
     */
    public void setPhone(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>sys_base.sys_user.phone</code>.
     */
    public String getPhone() {
        return (String) get(9);
    }

    /**
     * Setter for <code>sys_base.sys_user.birthday</code>.
     */
    public void setBirthday(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>sys_base.sys_user.birthday</code>.
     */
    public String getBirthday() {
        return (String) get(10);
    }

    /**
     * Setter for <code>sys_base.sys_user.password</code>.
     */
    public void setPassword(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>sys_base.sys_user.password</code>.
     */
    public String getPassword() {
        return (String) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row12<String, LocalDateTime, LocalDateTime, String, String, String, String, String, String, String, String, String> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    @Override
    public Row12<String, LocalDateTime, LocalDateTime, String, String, String, String, String, String, String, String, String> valuesRow() {
        return (Row12) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return SysUser.SYS_USER.ID;
    }

    @Override
    public Field<LocalDateTime> field2() {
        return SysUser.SYS_USER.CREATE_DATE;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return SysUser.SYS_USER.UPDATE_DATE;
    }

    @Override
    public Field<String> field4() {
        return SysUser.SYS_USER.ORG_ID;
    }

    @Override
    public Field<String> field5() {
        return SysUser.SYS_USER.DATA_LEVEL;
    }

    @Override
    public Field<String> field6() {
        return SysUser.SYS_USER.NAME;
    }

    @Override
    public Field<String> field7() {
        return SysUser.SYS_USER.AVATAR;
    }

    @Override
    public Field<String> field8() {
        return SysUser.SYS_USER.IDCARD;
    }

    @Override
    public Field<String> field9() {
        return SysUser.SYS_USER.SEX;
    }

    @Override
    public Field<String> field10() {
        return SysUser.SYS_USER.PHONE;
    }

    @Override
    public Field<String> field11() {
        return SysUser.SYS_USER.BIRTHDAY;
    }

    @Override
    public Field<String> field12() {
        return SysUser.SYS_USER.PASSWORD;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public LocalDateTime component2() {
        return getCreateDate();
    }

    @Override
    public LocalDateTime component3() {
        return getUpdateDate();
    }

    @Override
    public String component4() {
        return getOrgId();
    }

    @Override
    public String component5() {
        return getDataLevel();
    }

    @Override
    public String component6() {
        return getName();
    }

    @Override
    public String component7() {
        return getAvatar();
    }

    @Override
    public String component8() {
        return getIdcard();
    }

    @Override
    public String component9() {
        return getSex();
    }

    @Override
    public String component10() {
        return getPhone();
    }

    @Override
    public String component11() {
        return getBirthday();
    }

    @Override
    public String component12() {
        return getPassword();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public LocalDateTime value2() {
        return getCreateDate();
    }

    @Override
    public LocalDateTime value3() {
        return getUpdateDate();
    }

    @Override
    public String value4() {
        return getOrgId();
    }

    @Override
    public String value5() {
        return getDataLevel();
    }

    @Override
    public String value6() {
        return getName();
    }

    @Override
    public String value7() {
        return getAvatar();
    }

    @Override
    public String value8() {
        return getIdcard();
    }

    @Override
    public String value9() {
        return getSex();
    }

    @Override
    public String value10() {
        return getPhone();
    }

    @Override
    public String value11() {
        return getBirthday();
    }

    @Override
    public String value12() {
        return getPassword();
    }

    @Override
    public SysUserRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public SysUserRecord value2(LocalDateTime value) {
        setCreateDate(value);
        return this;
    }

    @Override
    public SysUserRecord value3(LocalDateTime value) {
        setUpdateDate(value);
        return this;
    }

    @Override
    public SysUserRecord value4(String value) {
        setOrgId(value);
        return this;
    }

    @Override
    public SysUserRecord value5(String value) {
        setDataLevel(value);
        return this;
    }

    @Override
    public SysUserRecord value6(String value) {
        setName(value);
        return this;
    }

    @Override
    public SysUserRecord value7(String value) {
        setAvatar(value);
        return this;
    }

    @Override
    public SysUserRecord value8(String value) {
        setIdcard(value);
        return this;
    }

    @Override
    public SysUserRecord value9(String value) {
        setSex(value);
        return this;
    }

    @Override
    public SysUserRecord value10(String value) {
        setPhone(value);
        return this;
    }

    @Override
    public SysUserRecord value11(String value) {
        setBirthday(value);
        return this;
    }

    @Override
    public SysUserRecord value12(String value) {
        setPassword(value);
        return this;
    }

    @Override
    public SysUserRecord values(String value1, LocalDateTime value2, LocalDateTime value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11, String value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SysUserRecord
     */
    public SysUserRecord() {
        super(SysUser.SYS_USER);
    }

    /**
     * Create a detached, initialised SysUserRecord
     */
    public SysUserRecord(String id, LocalDateTime createDate, LocalDateTime updateDate, String orgId, String dataLevel, String name, String avatar, String idcard, String sex, String phone, String birthday, String password) {
        super(SysUser.SYS_USER);

        set(0, id);
        set(1, createDate);
        set(2, updateDate);
        set(3, orgId);
        set(4, dataLevel);
        set(5, name);
        set(6, avatar);
        set(7, idcard);
        set(8, sex);
        set(9, phone);
        set(10, birthday);
        set(11, password);
    }
}
