/*
 * This file is generated by jOOQ.
 */
package com.rm.manager.jooq.tables.records;


import com.rm.manager.jooq.tables.SysUserRole;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysUserRoleRecord extends UpdatableRecordImpl<SysUserRoleRecord> implements Record5<String, LocalDateTime, LocalDateTime, String, String> {

    private static final long serialVersionUID = -1419031609;

    /**
     * Setter for <code>sys_base.sys_user_role.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>sys_base.sys_user_role.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>sys_base.sys_user_role.create_date</code>.
     */
    public void setCreateDate(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>sys_base.sys_user_role.create_date</code>.
     */
    public LocalDateTime getCreateDate() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>sys_base.sys_user_role.update_date</code>.
     */
    public void setUpdateDate(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>sys_base.sys_user_role.update_date</code>.
     */
    public LocalDateTime getUpdateDate() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>sys_base.sys_user_role.role_id</code>.
     */
    public void setRoleId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>sys_base.sys_user_role.role_id</code>.
     */
    public String getRoleId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>sys_base.sys_user_role.user_id</code>.
     */
    public void setUserId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>sys_base.sys_user_role.user_id</code>.
     */
    public String getUserId() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<String, LocalDateTime, LocalDateTime, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<String, LocalDateTime, LocalDateTime, String, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return SysUserRole.SYS_USER_ROLE.ID;
    }

    @Override
    public Field<LocalDateTime> field2() {
        return SysUserRole.SYS_USER_ROLE.CREATE_DATE;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return SysUserRole.SYS_USER_ROLE.UPDATE_DATE;
    }

    @Override
    public Field<String> field4() {
        return SysUserRole.SYS_USER_ROLE.ROLE_ID;
    }

    @Override
    public Field<String> field5() {
        return SysUserRole.SYS_USER_ROLE.USER_ID;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public LocalDateTime component2() {
        return getCreateDate();
    }

    @Override
    public LocalDateTime component3() {
        return getUpdateDate();
    }

    @Override
    public String component4() {
        return getRoleId();
    }

    @Override
    public String component5() {
        return getUserId();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public LocalDateTime value2() {
        return getCreateDate();
    }

    @Override
    public LocalDateTime value3() {
        return getUpdateDate();
    }

    @Override
    public String value4() {
        return getRoleId();
    }

    @Override
    public String value5() {
        return getUserId();
    }

    @Override
    public SysUserRoleRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public SysUserRoleRecord value2(LocalDateTime value) {
        setCreateDate(value);
        return this;
    }

    @Override
    public SysUserRoleRecord value3(LocalDateTime value) {
        setUpdateDate(value);
        return this;
    }

    @Override
    public SysUserRoleRecord value4(String value) {
        setRoleId(value);
        return this;
    }

    @Override
    public SysUserRoleRecord value5(String value) {
        setUserId(value);
        return this;
    }

    @Override
    public SysUserRoleRecord values(String value1, LocalDateTime value2, LocalDateTime value3, String value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SysUserRoleRecord
     */
    public SysUserRoleRecord() {
        super(SysUserRole.SYS_USER_ROLE);
    }

    /**
     * Create a detached, initialised SysUserRoleRecord
     */
    public SysUserRoleRecord(String id, LocalDateTime createDate, LocalDateTime updateDate, String roleId, String userId) {
        super(SysUserRole.SYS_USER_ROLE);

        set(0, id);
        set(1, createDate);
        set(2, updateDate);
        set(3, roleId);
        set(4, userId);
    }
}
