/*
 * This file is generated by jOOQ.
 */
package com.rm.manager.jooq.tables;


import com.rm.manager.jooq.Keys;
import com.rm.manager.jooq.SysBase;
import com.rm.manager.jooq.tables.records.SysDictionaryItemRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row7;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysDictionaryItem extends TableImpl<SysDictionaryItemRecord> {

    private static final long serialVersionUID = 1793474100;

    /**
     * The reference instance of <code>sys_base.sys_dictionary_item</code>
     */
    public static final SysDictionaryItem SYS_DICTIONARY_ITEM = new SysDictionaryItem();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SysDictionaryItemRecord> getRecordType() {
        return SysDictionaryItemRecord.class;
    }

    /**
     * The column <code>sys_base.sys_dictionary_item.id</code>.
     */
    public final TableField<SysDictionaryItemRecord, String> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>sys_base.sys_dictionary_item.create_date</code>.
     */
    public final TableField<SysDictionaryItemRecord, LocalDateTime> CREATE_DATE = createField(DSL.name("create_date"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>sys_base.sys_dictionary_item.update_date</code>.
     */
    public final TableField<SysDictionaryItemRecord, LocalDateTime> UPDATE_DATE = createField(DSL.name("update_date"), org.jooq.impl.SQLDataType.LOCALDATETIME.defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>sys_base.sys_dictionary_item.type_id</code>.
     */
    public final TableField<SysDictionaryItemRecord, String> TYPE_ID = createField(DSL.name("type_id"), org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>sys_base.sys_dictionary_item.key</code>.
     */
    public final TableField<SysDictionaryItemRecord, String> KEY = createField(DSL.name("key"), org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>sys_base.sys_dictionary_item.value</code>.
     */
    public final TableField<SysDictionaryItemRecord, String> VALUE = createField(DSL.name("value"), org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>sys_base.sys_dictionary_item.remark</code>.
     */
    public final TableField<SysDictionaryItemRecord, String> REMARK = createField(DSL.name("remark"), org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * Create a <code>sys_base.sys_dictionary_item</code> table reference
     */
    public SysDictionaryItem() {
        this(DSL.name("sys_dictionary_item"), null);
    }

    /**
     * Create an aliased <code>sys_base.sys_dictionary_item</code> table reference
     */
    public SysDictionaryItem(String alias) {
        this(DSL.name(alias), SYS_DICTIONARY_ITEM);
    }

    /**
     * Create an aliased <code>sys_base.sys_dictionary_item</code> table reference
     */
    public SysDictionaryItem(Name alias) {
        this(alias, SYS_DICTIONARY_ITEM);
    }

    private SysDictionaryItem(Name alias, Table<SysDictionaryItemRecord> aliased) {
        this(alias, aliased, null);
    }

    private SysDictionaryItem(Name alias, Table<SysDictionaryItemRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> SysDictionaryItem(Table<O> child, ForeignKey<O, SysDictionaryItemRecord> key) {
        super(child, key, SYS_DICTIONARY_ITEM);
    }

    @Override
    public Schema getSchema() {
        return SysBase.SYS_BASE;
    }

    @Override
    public UniqueKey<SysDictionaryItemRecord> getPrimaryKey() {
        return Keys.SYNTHETIC_PK_SYS_DICTIONARY_ITEM;
    }

    @Override
    public List<UniqueKey<SysDictionaryItemRecord>> getKeys() {
        return Arrays.<UniqueKey<SysDictionaryItemRecord>>asList(Keys.PK_SYS_DICTIONARY_ITEM, Keys.SYNTHETIC_PK_SYS_DICTIONARY_ITEM);
    }

    @Override
    public SysDictionaryItem as(String alias) {
        return new SysDictionaryItem(DSL.name(alias), this);
    }

    @Override
    public SysDictionaryItem as(Name alias) {
        return new SysDictionaryItem(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SysDictionaryItem rename(String name) {
        return new SysDictionaryItem(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SysDictionaryItem rename(Name name) {
        return new SysDictionaryItem(name, null);
    }

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row7<String, LocalDateTime, LocalDateTime, String, String, String, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }
}
