/*
 * This file is generated by jOOQ.
 */
package com.rm.manager.jooq.tables;


import com.rm.manager.jooq.Keys;
import com.rm.manager.jooq.SysBase;
import com.rm.manager.jooq.tables.records.SysMenuRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row8;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysMenu extends TableImpl<SysMenuRecord> {

    private static final long serialVersionUID = 1886757328;

    /**
     * The reference instance of <code>sys_base.sys_menu</code>
     */
    public static final SysMenu SYS_MENU = new SysMenu();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SysMenuRecord> getRecordType() {
        return SysMenuRecord.class;
    }

    /**
     * The column <code>sys_base.sys_menu.id</code>.
     */
    public final TableField<SysMenuRecord, String> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>sys_base.sys_menu.create_date</code>.
     */
    public final TableField<SysMenuRecord, LocalDateTime> CREATE_DATE = createField(DSL.name("create_date"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>sys_base.sys_menu.update_date</code>.
     */
    public final TableField<SysMenuRecord, LocalDateTime> UPDATE_DATE = createField(DSL.name("update_date"), org.jooq.impl.SQLDataType.LOCALDATETIME.defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>sys_base.sys_menu.name</code>.
     */
    public final TableField<SysMenuRecord, String> NAME = createField(DSL.name("name"), org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>sys_base.sys_menu.path</code>.
     */
    public final TableField<SysMenuRecord, String> PATH = createField(DSL.name("path"), org.jooq.impl.SQLDataType.VARCHAR(50).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>sys_base.sys_menu.pid</code>.
     */
    public final TableField<SysMenuRecord, String> PID = createField(DSL.name("pid"), org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false).defaultValue(org.jooq.impl.DSL.inline("'0'", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>sys_base.sys_menu.type</code>.
     */
    public final TableField<SysMenuRecord, String> TYPE = createField(DSL.name("type"), org.jooq.impl.SQLDataType.VARCHAR(2).nullable(false).defaultValue(org.jooq.impl.DSL.inline("'0'", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>sys_base.sys_menu.code</code>.
     */
    public final TableField<SysMenuRecord, String> CODE = createField(DSL.name("code"), org.jooq.impl.SQLDataType.VARCHAR(50).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * Create a <code>sys_base.sys_menu</code> table reference
     */
    public SysMenu() {
        this(DSL.name("sys_menu"), null);
    }

    /**
     * Create an aliased <code>sys_base.sys_menu</code> table reference
     */
    public SysMenu(String alias) {
        this(DSL.name(alias), SYS_MENU);
    }

    /**
     * Create an aliased <code>sys_base.sys_menu</code> table reference
     */
    public SysMenu(Name alias) {
        this(alias, SYS_MENU);
    }

    private SysMenu(Name alias, Table<SysMenuRecord> aliased) {
        this(alias, aliased, null);
    }

    private SysMenu(Name alias, Table<SysMenuRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> SysMenu(Table<O> child, ForeignKey<O, SysMenuRecord> key) {
        super(child, key, SYS_MENU);
    }

    @Override
    public Schema getSchema() {
        return SysBase.SYS_BASE;
    }

    @Override
    public UniqueKey<SysMenuRecord> getPrimaryKey() {
        return Keys.SYNTHETIC_PK_SYS_MENU;
    }

    @Override
    public List<UniqueKey<SysMenuRecord>> getKeys() {
        return Arrays.<UniqueKey<SysMenuRecord>>asList(Keys.PK_SYS_MENU, Keys.SYNTHETIC_PK_SYS_MENU);
    }

    @Override
    public SysMenu as(String alias) {
        return new SysMenu(DSL.name(alias), this);
    }

    @Override
    public SysMenu as(Name alias) {
        return new SysMenu(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SysMenu rename(String name) {
        return new SysMenu(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SysMenu rename(Name name) {
        return new SysMenu(name, null);
    }

    // -------------------------------------------------------------------------
    // Row8 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row8<String, LocalDateTime, LocalDateTime, String, String, String, String, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }
}
