/*
 * This file is generated by jOOQ.
 */
package com.rm.manager.jooq.tables;


import com.rm.manager.jooq.Keys;
import com.rm.manager.jooq.SysBase;
import com.rm.manager.jooq.tables.records.SysOrganizationRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row8;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysOrganization extends TableImpl<SysOrganizationRecord> {

    private static final long serialVersionUID = -944975278;

    /**
     * The reference instance of <code>sys_base.sys_organization</code>
     */
    public static final SysOrganization SYS_ORGANIZATION = new SysOrganization();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SysOrganizationRecord> getRecordType() {
        return SysOrganizationRecord.class;
    }

    /**
     * The column <code>sys_base.sys_organization.id</code>.
     */
    public final TableField<SysOrganizationRecord, String> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>sys_base.sys_organization.create_date</code>.
     */
    public final TableField<SysOrganizationRecord, LocalDateTime> CREATE_DATE = createField(DSL.name("create_date"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>sys_base.sys_organization.update_date</code>.
     */
    public final TableField<SysOrganizationRecord, LocalDateTime> UPDATE_DATE = createField(DSL.name("update_date"), org.jooq.impl.SQLDataType.LOCALDATETIME.defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>sys_base.sys_organization.name</code>.
     */
    public final TableField<SysOrganizationRecord, String> NAME = createField(DSL.name("name"), org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>sys_base.sys_organization.pid</code>.
     */
    public final TableField<SysOrganizationRecord, String> PID = createField(DSL.name("pid"), org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false).defaultValue(org.jooq.impl.DSL.inline("'0'", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>sys_base.sys_organization.full_id</code>.
     */
    public final TableField<SysOrganizationRecord, Integer> FULL_ID = createField(DSL.name("full_id"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>sys_base.sys_organization.remark</code>.
     */
    public final TableField<SysOrganizationRecord, String> REMARK = createField(DSL.name("remark"), org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>sys_base.sys_organization.location</code>.
     */
    public final TableField<SysOrganizationRecord, String> LOCATION = createField(DSL.name("location"), org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * Create a <code>sys_base.sys_organization</code> table reference
     */
    public SysOrganization() {
        this(DSL.name("sys_organization"), null);
    }

    /**
     * Create an aliased <code>sys_base.sys_organization</code> table reference
     */
    public SysOrganization(String alias) {
        this(DSL.name(alias), SYS_ORGANIZATION);
    }

    /**
     * Create an aliased <code>sys_base.sys_organization</code> table reference
     */
    public SysOrganization(Name alias) {
        this(alias, SYS_ORGANIZATION);
    }

    private SysOrganization(Name alias, Table<SysOrganizationRecord> aliased) {
        this(alias, aliased, null);
    }

    private SysOrganization(Name alias, Table<SysOrganizationRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> SysOrganization(Table<O> child, ForeignKey<O, SysOrganizationRecord> key) {
        super(child, key, SYS_ORGANIZATION);
    }

    @Override
    public Schema getSchema() {
        return SysBase.SYS_BASE;
    }

    @Override
    public UniqueKey<SysOrganizationRecord> getPrimaryKey() {
        return Keys.SYNTHETIC_PK_SYS_ORGANIZATION;
    }

    @Override
    public List<UniqueKey<SysOrganizationRecord>> getKeys() {
        return Arrays.<UniqueKey<SysOrganizationRecord>>asList(Keys.PK_SYS_ORGANIZATION, Keys.SYNTHETIC_PK_SYS_ORGANIZATION);
    }

    @Override
    public SysOrganization as(String alias) {
        return new SysOrganization(DSL.name(alias), this);
    }

    @Override
    public SysOrganization as(Name alias) {
        return new SysOrganization(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SysOrganization rename(String name) {
        return new SysOrganization(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SysOrganization rename(Name name) {
        return new SysOrganization(name, null);
    }

    // -------------------------------------------------------------------------
    // Row8 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row8<String, LocalDateTime, LocalDateTime, String, String, Integer, String, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }
}
